# Generated by Django 4.2.13 on 2024-07-09 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('postcode', models.CharField()),
                ('county', models.CharField(choices=[('Bedfordshire', 'Bedfordshire'), ('Berkshire', 'Berkshire'), ('Buckinghamshire', 'Buckinghamshire'), ('Berwickshire', 'Berwickshire'), ('cheshire', 'cheshire'), ('cornwall', 'cornwall'), ('Dovan', 'Dovan'), ('Dorset', 'Dorset'), ('Hampshire', 'Hampshire'), ('Kent', 'Kent'), ('Yorkshire', 'Yorkshire')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
