# Generated by Django 4.2.13 on 2024-07-12 19:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='product'),
        ),
    ]
